version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  app:
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    command: yarn prod

volumes:
  postgres_data:
